### ISSUE TITLE
[PATH] báo cáo công việc 26/9

### ISSUE THREAD

**Issue by tiennh-0852** [truonganhhoang/int3507-2016#52]

**Comment by ducanhk58uet** [comment]
Yêu cầu của thầy (server-communication)
• HTTP client sample overview **[DONE]** -> Phượng
• Fetch data with http.get **[DONE]** -> Phượng
• RxJS Observale of HTTP Response **[DONE]** -> Tiến
• Enabing RxJS Operators -> Tiến
• Extract JSON data **[DONE]** -> Tiến
• Error handling  -> Đức Anh
• Send data to the server **[DONE]** -> Tiến
• Promises instead of obver -> Đức Anh
• Cross-orgin requests **[DONE]**  -> Đức Anh
• Appendix: the in-memory web api service.

Định hướng phát triển trong thời gian tới
• Thiết kế cơ sở dữ liệu (MongDB) **[DONE]** -> Đức Anh
• Xây dựng giao diện cho website (sử dụng boostrap) -> Tiến, Phượng
• Crawl data từ các nguồn khác -> Đức Anh
• Demo với một bài test đơn giản (trắc nghiệm) -> Tiến, Phượng, Đ.A

**Comment by ducanhk58uet** [comment]
Viết xong script insert dữ liệu cho Home, viết api cho trang Home
Chờ Phượng + Tiến làm xong giao diện, đổ dữ liệu vào giao diện.

**Comment by tiennh-0852** [comment]
Đã viết xong tìm hiểu kiến thức, làm slide chuẩn bị thuyết trình

**Comment by phuongnt58** [comment]
Xong giao diện trang home + tìm hiểu nâng cao angular 2.0 về Server communication

**Comment by tiennh-0852** [comment]
làm xong trang detail

**Comment by phuongnt58** [comment]
tìm hiểu testing trong angular
